pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven { url = 'https://maven.parchmentmc.org' } // Add this line
        maven { url = "https://repo.spongepowered.org/maven" }

    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}
rootProject.name = "c-mc165f"
include(":c-mc-common")
project(":c-mc-common").projectDir = file("../common")