<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <TrimMode>full</TrimMode>
    <StripSymbols>true</StripSymbols>
    <AssemblyName>rdi-installer</AssemblyName>
    <ApplicationIcon>..\src\main\resources\icon.ico</ApplicationIcon>
    <AssemblyTitle>RDI Client Installer</AssemblyTitle>
    <Description>RDI Client Installer</Description>
    <Product>rdi</Product>
    <Copyright>calebxzau</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Form1.cs;Form1.Designer.cs;Win32InstallerApp.cs" />
    <EmbeddedResource Include="assets\client.tar.zst" LogicalName="client.tar.zst" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>

</Project>
