plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version '2.4.0'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.4.0'

}

group = "calebxzhou.rdi.mc.rmcp"
version = "0.1"


repositories {
    mavenLocal()
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

kotlin {
    jvmToolchain(25)
    sourceSets.all {
        languageSettings {
            optIn("kotlinx.serialization.ExperimentalSerializationApi")
        }
    }
}
sourceSets.named('main') {
    kotlin.srcDir '../../../ktutils/std/src/main/kotlin'
}
dependencies{
    //implementation("de.brudaswen.kotlinx.serialization:kotlinx-serialization-csv:3.2.1")
    implementation 'io.fusionauth:java-http:1.4.0'
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
    implementation("io.heapy.kotaml:kotaml:0.108.0")
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
