pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = uri("https://maven.neoforged.net/releases") }
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "s21"

include(":s-mc-common")
project(":s-mc-common").projectDir = file("../common")
include(":rmcp-common")
project(":rmcp-common").projectDir = file("../../../mc/rmcp/common")
include(":rmcp-server")
project(":rmcp-server").projectDir = file("../../../mc/rmcp/server")
/*include(":ktutils-std")
project(":ktutils-std").projectDir = file("../../../ktutils/std")*/

