className=calebxzhou.rdi.client.MainKt
funName=main
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx4G
# Gradle daemon空闲10分钟后自动退出，避免大量僵尸进程(zombie process)
org.gradle.daemon.idletimeout=600000
kotlin.daemon.options.autoshutdownIdleSeconds=7200
