package calebxzhou.rdi.client.model

import calebxzau.rdi.mclaunch.model.MojangArguments as MclaunchMojangArguments
import calebxzau.rdi.mclaunch.model.MojangAssetIndex as MclaunchMojangAssetIndex
import calebxzau.rdi.mclaunch.model.MojangAssetIndexFile as MclaunchMojangAssetIndexFile
import calebxzau.rdi.mclaunch.model.MojangAssetObject as MclaunchMojangAssetObject
import calebxzau.rdi.mclaunch.model.MojangDownloadArtifact as MclaunchMojangDownloadArtifact
import calebxzau.rdi.mclaunch.model.MojangJavaVersion as MclaunchMojangJavaVersion
import calebxzau.rdi.mclaunch.model.MojangLibrary as MclaunchMojangLibrary
import calebxzau.rdi.mclaunch.model.MojangLibraryDownloads as MclaunchMojangLibraryDownloads
import calebxzau.rdi.mclaunch.model.MojangLoggingConfig as MclaunchMojangLoggingConfig
import calebxzau.rdi.mclaunch.model.MojangLoggingFile as MclaunchMojangLoggingFile
import calebxzau.rdi.mclaunch.model.MojangRule as MclaunchMojangRule
import calebxzau.rdi.mclaunch.model.MojangRuleAction as MclaunchMojangRuleAction
import calebxzau.rdi.mclaunch.model.MojangRuleOs as MclaunchMojangRuleOs
import calebxzau.rdi.mclaunch.model.MojangVersionDownloads as MclaunchMojangVersionDownloads
import calebxzau.rdi.mclaunch.model.MojangVersionManifest as MclaunchMojangVersionManifest

typealias MojangVersionManifest = MclaunchMojangVersionManifest
typealias MojangArguments = MclaunchMojangArguments
typealias MojangVersionDownloads = MclaunchMojangVersionDownloads
typealias MojangDownloadArtifact = MclaunchMojangDownloadArtifact
typealias MojangAssetIndex = MclaunchMojangAssetIndex
typealias MojangAssetIndexFile = MclaunchMojangAssetIndexFile
typealias MojangAssetObject = MclaunchMojangAssetObject
typealias MojangLoggingConfig = MclaunchMojangLoggingConfig
typealias MojangLoggingFile = MclaunchMojangLoggingFile
typealias MojangJavaVersion = MclaunchMojangJavaVersion
typealias MojangLibrary = MclaunchMojangLibrary
typealias MojangLibraryDownloads = MclaunchMojangLibraryDownloads
typealias MojangRule = MclaunchMojangRule
typealias MojangRuleAction = MclaunchMojangRuleAction
typealias MojangRuleOs = MclaunchMojangRuleOs
