plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7+'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

base {
    archivesName = "rdi"
}

version = "5-mc-server-${mcVersion}-forge"
evaluationDependsOn(":s-mc-common")

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        name = "Forge Maven"
        url = "https://maven.minecraftforge.net/"
    }
}

java {
    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
}

mixin {
    add sourceSets.main, "rdi.mixins.refmap.json"
    config "rdi.mixins.json"  // Add this line
    debug.verbose = true
    debug.export = true
}
minecraft {
    mappings channel: 'parchment', version: "2022.03.06-${project.mcVersion}"

    runs {
        server {
            properties 'forge.logging.markers': ''
            properties 'forge.logging.console.level': 'debug'
            workingDirectory project.file('run').canonicalPath
            source sourceSets.main
            properties "rdi.ihq.url": "127.0.0.1:65231"
            properties "rdi.host.id": "695f9e5ad05510e77c09ea1a"
           // arg "-mixin.debug=true"
            //arg "-mixin.checks.interfaces=true"
            arg "-mixin.config=rdi.mixins.json"
            arg "--nogui"
        }
    }
}

sourceSets {
    main {
        java {
            srcDir project(":s-mc-common").sourceSets.main.java.srcDirs
        }
    }
}
def shadedConfiguration = configurations.maybeCreate('shaded')

dependencies {
    minecraft "net.minecraftforge:forge:${project.mcVersion}-${project.forgeVersion}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    evaluationDependsOn(':s-mc-common')
    implementation project(':s-mc-common')
    implementation 'com.neovisionaries:nv-websocket-client:2.14'
    shaded 'com.neovisionaries:nv-websocket-client:2.14'
}

tasks.named('jar') {
    archiveClassifier = ''
}

jar {
    from({
        shadedConfiguration.collect { it.isDirectory() ? it : zipTree(it) }
    }) {
        exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    }
    from(sourceSets.main.output) {
        include "rdi.mixins.refmap.json"
    }
    manifest {
        attributes(["Specification-Title"     : project.name,
                    "Specification-Vendor"    : project.author,
                    "Specification-Version"   : "24.0",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.version,
                    "Implementation-Vendor"   : project.author,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    "MixinConfigs"            : "rdi.mixins.json"],)
    }
}
evaluationDependsOn(':s-mc-common')
project(':s-mc-common').ext.registerServerCopyTask(project)
