<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>..\src\main\resources\icon.ico</ApplicationIcon>
    <Description>RDI Client Updater</Description>
    <Copyright>calebxzau</Copyright>
  </PropertyGroup>

</Project>
